const routes = {
    admin: {
        dashboard: '/admin',
        review: '/admin/review',
        account: '/admin/account',
        employee: '/admin/employee',
        employee_create: '/admin/employee/create',
        employee_update: '/admin/employee/update',
        employee_update_id: '/admin/employee/update/:id',
        sale: '/admin/sale',
        sale_create: '/admin/sale/create',
        sale_update: '/admin/sale/update',
        sale_update_id: '/admin/sale/update/:id',
        delivery: '/admin/delivery',
        delivery_create: '/admin/delivery/create',
        delivery_update: '/admin/delivery/update',
        delivery_update_id: '/admin/delivery/update/:id',
        payment_method: '/admin/payment-method',
        payment_method_create: '/admin/payment-method/create',
        payment_method_update: '/admin/payment-method/update',
        payment_method_update_id: '/admin/payment-method/update/:id',
        transaction: '/admin/transaction',
    },
    web: {
        register: '/register',
        login: '/login',
        home: '/home',
        cart: '/cart',
        checkout: '/checkout',
        shop: 'shop',
        product_detail: 'product-detail',
        product: '/products',
        profile: '/user/profile',
        address: '/user/address',
        favorites: '/user/favorites',
        password: '/user/password',
        order: '/user/order',
        order_detail: '/user/order/:id',
        notification: '/user/notification',
    },
};
export default routes;
