const routes = {
    admin: {
        dashboard: '/admin',
        // Product
        product: '/admin/products',
        product_create: '/admin/products/create',
        product_update: '/admin/products/update',
        // Category
        category: '/admin/categories',
        category_create: '/admin/categories/create',
        category_update: '/admin/categories/update',
        // Unit
        unit: '/admin/units',
        unit_create: '/admin/units/create',
        unit_update: '/admin/units/update',
        // Brand
        brand: '/admin/brands',
        brand_create: '/admin/brands/create',
        brand_update: '/admin/brands/update',
        // Inventory
        inventory: '/admin/inventories',
        // Order
        order: '/admin/orders',
        order_update: '/admin/orders/update',
        reason_cancel: '/admin/orders/reasons-cancel',
        reason_cancel_create: '/admin/orders/reasons-cancel/create',
        reason_cancel_update: '/admin/orders/reasons-cancel/update',
        // Review
        review: '/admin/review',
        // Account
        account: '/admin/account',
        // Employee
        employee: '/admin/employee',
        employee_create: '/admin/employee/create',
        employee_update: '/admin/employee/update',
        employee_update_id: '/admin/employee/update/:id',
        // Sale
        sale: '/admin/sale',
        sale_create: '/admin/sale/create',
        sale_update: '/admin/sale/update',
        sale_update_id: '/admin/sale/update/:id',
        // Delivery
        delivery: '/admin/delivery',
        delivery_create: '/admin/delivery/create',
        delivery_update: '/admin/delivery/update',
        delivery_update_id: '/admin/delivery/update/:id',
        // Payment
        payment_method: '/admin/payment-method',
        payment_method_create: '/admin/payment-method/create',
        payment_method_update: '/admin/payment-method/update',
        payment_method_update_id: '/admin/payment-method/update/:id',
        // Transaction
        transaction: '/admin/transaction',
    },
    web: {
        register: '/register',
        login: '/login',
        home: '/home',
        cart: '/cart',
        checkout: '/checkout',
        shop: 'shop',
        product_detail: 'product-detail',
        product: '/products',
        profile: '/user/profile',
        address: '/user/address',
        favorites: '/user/favorites',
        password: '/user/password',
        order: '/user/order',
        order_detail: '/user/order/:id',
        notification: '/user/notification',
    },
};
export default routes;
